Proxy_path = /afs/ifh.de/user/f/freder/x509up_u37827
cpus = 1

executable              = /lustre/fs22/group/atlas/freder/hh/hh-analysis/HistFillFile.sh
log                     = log_$(Process).log
output                  = outfile_$(Process).txt
error                   = errors_$(Process).txt
should_transfer_files   = No
# when_to_transfer_output = ON_EXIT
request_cpus = $(cpus)
# request_memory = 8G
# request_disk = 20G
getenv = True

arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000020.output-hh4b.root
deferral_time = (CurrentTime + 10)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000015.output-hh4b.root
deferral_time = (CurrentTime + 20)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000007.output-hh4b.root
deferral_time = (CurrentTime + 30)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000002.output-hh4b.root
deferral_time = (CurrentTime + 40)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000003.output-hh4b.root
deferral_time = (CurrentTime + 50)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000014.output-hh4b.root
deferral_time = (CurrentTime + 60)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000019.output-hh4b.root
deferral_time = (CurrentTime + 70)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000013.output-hh4b.root
deferral_time = (CurrentTime + 80)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000005.output-hh4b.root
deferral_time = (CurrentTime + 90)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000006.output-hh4b.root
deferral_time = (CurrentTime + 100)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000022.output-hh4b.root
deferral_time = (CurrentTime + 110)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000021.output-hh4b.root
deferral_time = (CurrentTime + 120)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000004.output-hh4b.root
deferral_time = (CurrentTime + 130)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000017.output-hh4b.root
deferral_time = (CurrentTime + 140)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000016.output-hh4b.root
deferral_time = (CurrentTime + 150)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000001.output-hh4b.root
deferral_time = (CurrentTime + 160)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000018.output-hh4b.root
deferral_time = (CurrentTime + 170)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000011.output-hh4b.root
deferral_time = (CurrentTime + 180)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000009.output-hh4b.root
deferral_time = (CurrentTime + 190)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000010.output-hh4b.root
deferral_time = (CurrentTime + 200)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5057_TREE/user.dabattul.31380309._000008.output-hh4b.root
deferral_time = (CurrentTime + 210)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000017.output-hh4b.root
deferral_time = (CurrentTime + 220)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000027.output-hh4b.root
deferral_time = (CurrentTime + 230)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000029.output-hh4b.root
deferral_time = (CurrentTime + 240)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000026.output-hh4b.root
deferral_time = (CurrentTime + 250)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000012.output-hh4b.root
deferral_time = (CurrentTime + 260)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000005.output-hh4b.root
deferral_time = (CurrentTime + 270)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000018.output-hh4b.root
deferral_time = (CurrentTime + 280)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000016.output-hh4b.root
deferral_time = (CurrentTime + 290)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000019.output-hh4b.root
deferral_time = (CurrentTime + 300)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000013.output-hh4b.root
deferral_time = (CurrentTime + 310)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000021.output-hh4b.root
deferral_time = (CurrentTime + 320)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000003.output-hh4b.root
deferral_time = (CurrentTime + 330)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000025.output-hh4b.root
deferral_time = (CurrentTime + 340)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000020.output-hh4b.root
deferral_time = (CurrentTime + 350)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000001.output-hh4b.root
deferral_time = (CurrentTime + 360)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000028.output-hh4b.root
deferral_time = (CurrentTime + 370)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000014.output-hh4b.root
deferral_time = (CurrentTime + 380)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000011.output-hh4b.root
deferral_time = (CurrentTime + 390)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000009.output-hh4b.root
deferral_time = (CurrentTime + 400)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000010.output-hh4b.root
deferral_time = (CurrentTime + 410)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000015.output-hh4b.root
deferral_time = (CurrentTime + 420)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000002.output-hh4b.root
deferral_time = (CurrentTime + 430)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000024.output-hh4b.root
deferral_time = (CurrentTime + 440)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000007.output-hh4b.root
deferral_time = (CurrentTime + 450)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000006.output-hh4b.root
deferral_time = (CurrentTime + 460)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000008.output-hh4b.root
deferral_time = (CurrentTime + 470)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000004.output-hh4b.root
deferral_time = (CurrentTime + 480)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13145_p5057_TREE/user.dabattul.31380312._000023.output-hh4b.root
deferral_time = (CurrentTime + 490)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000002.output-hh4b.root
deferral_time = (CurrentTime + 500)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000005.output-hh4b.root
deferral_time = (CurrentTime + 510)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000003.output-hh4b.root
deferral_time = (CurrentTime + 520)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000012.output-hh4b.root
deferral_time = (CurrentTime + 530)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000007.output-hh4b.root
deferral_time = (CurrentTime + 540)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000008.output-hh4b.root
deferral_time = (CurrentTime + 550)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000011.output-hh4b.root
deferral_time = (CurrentTime + 560)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000006.output-hh4b.root
deferral_time = (CurrentTime + 570)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000001.output-hh4b.root
deferral_time = (CurrentTime + 580)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000004.output-hh4b.root
deferral_time = (CurrentTime + 590)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000010.output-hh4b.root
deferral_time = (CurrentTime + 600)
queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/dbattulga/ntup_SH_Oct20/bkg/user.dabattul.ntup_251122.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13167_p5057_TREE/user.dabattul.31380314._000009.output-hh4b.root
deferral_time = (CurrentTime + 610)
queue
