Proxy_path = /afs/ifh.de/user/f/freder/x509up_u37827
cpus = 1

executable              = /lustre/fs22/group/atlas/freder/hh/hh-analysis/batch/HistFillFile.sh
log                     = log_$(Process).log
output                  = outfile_$(Process).txt
error                   = errors_$(Process).txt
should_transfer_files   = No
# when_to_transfer_output = ON_EXIT
request_cpus = $(cpus)
getenv = True

arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/freder/hh/samples/user.frenner.HH4b.2022_12_14.502970.MGPy8EG_hh_bbbb_vbf_novhh_l1cvv1cv1.e8263_s3681_r13144_p5440_TREE/user.frenner.31601111._000001.output-hh4b.root

queue
arguments = $(Proxy_path) $(cpus) /lustre/fs22/group/atlas/freder/hh/samples/user.frenner.HH4b.2022_12_14.502970.MGPy8EG_hh_bbbb_vbf_novhh_l1cvv1cv1.e8263_s3681_r13167_p5440_TREE/user.frenner.31601113._000001.output-hh4b.root

queue
